### ISSUE TITLE
VanillaEnchants fails to enable

### ISSUE THREAD

**Issue by squishycat92** [AD-Wright/VanillaEnchants#2]
Hello, upon enabling this plugin on my server I get a message telling me that VanillaEnchants failed to enable. I have tried building it myself in Eclipse IDE and using the one that AD-Wright suggested in koenrad's issues page. The following error message is what I get on Purpur 1.16.4:
`[20:37:39 ERROR]: Error occurred while enabling VanillaEnchants v1.3 (Is it up to date?)
java.lang.NullPointerException: null
	at network.kngsgaming.minecraft.EnchantEvents.<init>(EnchantEvents.java:35) ~[?:?]
	at network.kngsgaming.minecraft.VanillaEnchants.onEnable(VanillaEnchants.java:35) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Purpur-880]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Purpur-880]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Purpur-880]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Purpur-880]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Purpur-880]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:945) ~[patched_1.16.4.jar:git-Purpur-880]
	at org.bukkit.Bukkit.reload(Bukkit.java:699) ~[patched_1.16.4.jar:git-Purpur-880]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.4.jar:git-Purpur-880]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.4.jar:git-Purpur-880]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2058) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1861) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1814) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1205) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1198) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1174) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1018) ~[patched_1.16.4.jar:git-Purpur-880]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180) ~[patched_1.16.4.jar:git-Purpur-880]
	at java.lang.Thread.run(Thread.java:830) [?:?]
[20:37:39 INFO]: Disabling VanillaEnchants v1.3`

Any reason why and how to fix? I'd really like to get this plugin working! I've tried /reload confirm and restarting the server already.

Thanks in advance!

**Comment by AD-Wright** [comment]
I noticed you forked the repository - did removing that whitespace resolve your issue?

**Comment by squishycat92** [comment]
Unfortunately, it did not.

**Comment by AD-Wright** [comment]
Interesting.  I've tried to replicate the issue, using purpur 880 and various built jars.  Haven't had any luck so far.  I have included a jar in this repository as well now (in the `target` folder), perhaps try that? 

Are you using any additional mods?

**Comment by squishycat92** [comment]
No, we are not using any additional mods. Interestingly, my fork worked for a little while, but now it's giving the same `nullPointerException` error.

**Comment by AD-Wright** [comment]
What operating system is the server running on?  Windows 10, Ubuntu, MacOS?

**Comment by squishycat92** [comment]
It is running on macOS 10.15.7

**Comment by AD-Wright** [comment]
And what happens if you try editing and then saving the config.yml file?  Did it stop working once you had edited the file?

**Comment by squishycat92** [comment]
Yes, after I edited the file to have a blank `limits:` section (so everything has no limit) it stopped working.

**Comment by AD-Wright** [comment]
Interesting.  Try putting a nonsensical enchantment in instead of having an empty limits section.  Something like: 
```
limits:  
  fake: 5
```
Make sure you get the spacing right, it's two spaces before `fake` in this case.

**Comment by squishycat92** [comment]
Sure! I'll try that and tell you the result.

**Comment by squishycat92** [comment]
Yay! Adding that to the config fixes the `nullErrorPointerException`! I guess you can't leave the config blank or else it will recognize it as null 👍
